#!/bin/sh

# This shell script automates deletes all installed libs

echo ""
echo "-------------------------------------------------------------------"
echo "DELETING Build Tools (using APK / Alpine)"
echo "-------------------------------------------------------------------"
echo ""

apk del        \
  tar          \
  wget         \
  git          \
  pkgconf      \
  ruby         \
  cmake        \
  make         \
  gcc          \
  g++          \
  gettext      \
  openjdk8     \
  jq           \
  sqlite
