#!/bin/sh

# This shell script automates getting the required build tools (apt install)

# set the shell environment variable 'UNATTENDED' to '--assume-yes' for
# unattended use (for example in the .travis.yml script)

echo ""
echo "-------------------------------------------------------------------"
echo "INSTALLING Build Tools (using APK / Alpine)"
echo "-------------------------------------------------------------------"
echo ""

set -ev

apk update
apk add        \
  tar          \
  wget         \
  git          \
  pkgconfig    \
  ruby         \
  cmake~=3.17 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.12/main  \
  make         \
  gcc          \
  g++          \
  gettext      \
  openjdk8     \
  jq
